# Generated by Django 2.1.7 on 2019-06-18 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_face', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resorts',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
