# Generated by Django 2.1.7 on 2019-06-21 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_face', '0002_resorts_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='resort_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_face.Resorts', unique=True),
        ),
    ]
