# Generated by Django 2.1.7 on 2019-07-03 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_face', '0004_reports_resort_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='resort_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
