# Generated by Django 2.1.7 on 2019-07-04 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_face', '0005_auto_20190703_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
