# Generated by Django 2.1.7 on 2019-07-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_face', '0006_reports_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
    ]
